customhost = "employee.c8ze40mty7gy.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "tansukchuang-employee"
customregion = "us-east-1"
